// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" }); // fallback
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL per le migrazioni (connessione diretta, no pooler)
    // DATABASE_URL per il runtime (pgbouncer)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
